In [2]:
import numpy as np
import pandas as pd

In [3]:
data=pd.Series([0.25, 0.5,0.75,1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

In [4]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

In [5]:
data.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
data[1]

0.5

In [11]:
data=pd.Series([0.1,0.2,0.3,0.4], index=['a','b','c','d'])
data

a    0.1
b    0.2
c    0.3
d    0.4
dtype: float64

In [12]:
data['b']

0.2

In [13]:
population_dict={'CA':150,'TX':200,'NY':120,'FL':195,'IL':128}
population=pd.Series(population_dict)
population

CA    150
TX    200
NY    120
FL    195
IL    128
dtype: int64

In [14]:
population['CA']

150

In [15]:
population['CA':'FL']

CA    150
TX    200
NY    120
FL    195
dtype: int64

In [16]:
area_dict={'CA': 423, 'TX':695, 'NY':141, 'FL':170, 'IL':149}
area=pd.Series(area_dict)
area

CA    423
TX    695
NY    141
FL    170
IL    149
dtype: int64

In [18]:
states = pd.DataFrame({'population': population, 'area': area})
states

population  area
CA         150   423
TX         200   695
NY         120   141
FL         195   170
IL         128   149

In [19]:
states['area']

CA    423
TX    695
NY    141
FL    170
IL    149
Name: area, dtype: int64

In [20]:
pd.DataFrame(population, columns=['population'])

population
CA         150
TX         200
NY         120
FL         195
IL         128

In [21]:
data = [{'a':i, 'b':2*i}
       for i in range(3)]
pd.DataFrame(data)

a  b
0  0  0
1  1  2
2  2  4

In [22]:
pd.DataFrame([{'a':1, 'b':2}, {'b':3, 'c':4}])

a  b    c
0  1.0  2  NaN
1  NaN  3  4.0

In [23]:
pd.DataFrame(np.random.rand(3,2), columns=['foo','bar'], index=['a','b','c'])

foo       bar
a  0.461268  0.746967
b  0.889649  0.506296
c  0.229402  0.007323

In [24]:
ind = pd.Index([2,3,5,7,11])
ind

Int64Index([2, 3, 5, 7, 11], dtype='int64')

In [25]:
ind.shape

(5,)

In [26]:
ind[1]

3

In [27]:
ind[::2]

Int64Index([2, 5, 11], dtype='int64')

In [4]:
import pandas as pd
data = pd.Series([0.25,0.5,0.75,1.0], index=['a','b','c','d'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [6]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [8]:
data[0:2]  # 암묵적 인덱싱

a    0.25
b    0.50
dtype: float64

In [9]:
data[(data>0.3) & (data<0.8)] # 조건절은 마스크 -> 인덱싱

b    0.50
c    0.75
dtype: float64

In [12]:
data[['a','d']]  # 팬시 인덱싱

a    0.25
d    1.00
dtype: float64

In [13]:
data = pd.Series(['a','b','c'], index=[1,3,5])
data

1    a
3    b
5    c
dtype: object

In [16]:
data.loc[1]  # 명시적 인덱스

'a'

In [17]:
data.iloc[1]  # 암묵적 인덱스

'b'

In [32]:
area = pd.Series({'California':423967,'Texas':695662,'Florida':170312,'New York':141297,'Pennysylvania':119280})
pop = pd.Series({'California':39538223,'Texas':29145505,'Florida':21538187,'New York':20201249,'Pennysylvania':13002700})
data = pd.DataFrame({'area':area,'pop':pop})
data

area       pop
California     423967  39538223
Texas          695662  29145505
Florida        170312  21538187
New York       141297  20201249
Pennysylvania  119280  13002700

In [33]:
data['area'] # 컬럼을 뽑았다 - 인덱싱

California       423967
Texas            695662
Florida          170312
New York         141297
Pennysylvania    119280
Name: area, dtype: int64

In [34]:
data.area 

California       423967
Texas            695662
Florida          170312
New York         141297
Pennysylvania    119280
Name: area, dtype: int64

In [35]:
data['density'] = data['pop'] / data['area']
data

area       pop     density
California     423967  39538223   93.257784
Texas          695662  29145505   41.896072
Florida        170312  21538187  126.463121
New York       141297  20201249  142.970120
Pennysylvania  119280  13002700  109.009893

In [36]:
data.index

Index(['California', 'Texas', 'Florida', 'New York', 'Pennysylvania'], dtype='object')

In [37]:
data.values

array([[4.23967000e+05, 3.95382230e+07, 9.32577842e+01],
       [6.95662000e+05, 2.91455050e+07, 4.18960717e+01],
       [1.70312000e+05, 2.15381870e+07, 1.26463121e+02],
       [1.41297000e+05, 2.02012490e+07, 1.42970120e+02],
       [1.19280000e+05, 1.30027000e+07, 1.09009893e+02]])

In [38]:
data.T

California         Texas       Florida      New York  Pennysylvania
area     4.239670e+05  6.956620e+05  1.703120e+05  1.412970e+05   1.192800e+05
pop      3.953822e+07  2.914550e+07  2.153819e+07  2.020125e+07   1.300270e+07
density  9.325778e+01  4.189607e+01  1.264631e+02  1.429701e+02   1.090099e+02

In [39]:
data.values[0] # 암묵적 인덱스

array([4.23967000e+05, 3.95382230e+07, 9.32577842e+01])

In [40]:
data['area']

California       423967
Texas            695662
Florida          170312
New York         141297
Pennysylvania    119280
Name: area, dtype: int64

In [41]:
data.iloc[:3,:2]

area       pop
California  423967  39538223
Texas       695662  29145505
Florida     170312  21538187

In [43]:
data.loc[:'Florida',:'pop'] # 슬라이싱 + 명시적 인덱스

area       pop
California  423967  39538223
Texas       695662  29145505
Florida     170312  21538187

In [44]:
data['area'] # 열에 대한 인덱스

California       423967
Texas            695662
Florida          170312
New York         141297
Pennysylvania    119280
Name: area, dtype: int64

In [45]:
data['Florida':'New York'] # 슬라이싱은 행에 대하여 적용

area       pop     density
Florida   170312  21538187  126.463121
New York  141297  20201249  142.970120

In [46]:
import pandas as pd
import numpy as np
rng = np.random.RandomState(42)
ser = pd.Series(rng.randint(0,10,4))
ser

0    6
1    3
2    7
3    4
dtype: int32

In [49]:
df = pd.DataFrame(rng.randint(0,10,(3,4)), columns=['A','B','C','D'])
df

A  B  C  D
0  1  7  5  1
1  4  0  9  5
2  8  0  9  2

In [50]:
np.exp(ser)

0     403.428793
1      20.085537
2    1096.633158
3      54.598150
dtype: float64

In [51]:
np.sin(df*np.pi/4)

A         B         C         D
0  7.071068e-01 -0.707107 -0.707107  0.707107
1  1.224647e-16  0.000000  0.707107 -0.707107
2 -2.449294e-16  0.000000  0.707107  1.000000

In [52]:
area = pd.Series({'Alaska':1723337,'Texas':695662,'California':423967}, name='area')
population = pd.Series({'California':423967,'Texas':695662, 'New York':19651127}, name='population')

In [53]:
population / area

Alaska        NaN
California    1.0
New York      NaN
Texas         1.0
dtype: float64

In [54]:
area.index | population.index

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead
  """Entry point for launching an IPython kernel.


Index(['Alaska', 'California', 'New York', 'Texas'], dtype='object')

In [55]:
A = pd.Series([2,4,6], index=[0,1,2])
B = pd.Series([1,3,5], index=[1,2,3])

In [56]:
A + B

0    NaN
1    5.0
2    9.0
3    NaN
dtype: float64

In [57]:
A.add(B, fill_value=0)

0    2.0
1    5.0
2    9.0
3    5.0
dtype: float64

In [58]:
A = rng.randint(10, size=(3,4))
A

array([[6, 3, 8, 2],
       [4, 2, 6, 4],
       [8, 6, 1, 3]])

In [59]:
A - A[0]  # 2차원 데이터프레임 - 1차원 시리즈 => 브로드캐스팅하여 element=wise 연산

array([[ 0,  0,  0,  0],
       [-2, -1, -2,  2],
       [ 2,  3, -7,  1]])

In [60]:
A[0]

array([6, 3, 8, 2])

In [61]:
df = pd.DataFrame(A, columns=list('QRST'))

In [64]:
df

Q  R  S  T
0  6  3  8  2
1  4  2  6  4
2  8  6  1  3

In [62]:
df.iloc[0]

Q    6
R    3
S    8
T    2
Name: 0, dtype: int32

In [65]:
df - df.iloc[0]

Q  R  S  T
0  0  0  0  0
1 -2 -1 -2  2
2  2  3 -7  1

In [67]:
df.subtract(df['R'], axis=0)

Q  R  S  T
0  3  0  5 -1
1  2  0  4  2
2  2  0 -5 -3

In [68]:
vals1=np.array([1,None,2,3])
vals1

array([1, None, 2, 3], dtype=object)

In [69]:
vals1.sum()

TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'

In [70]:
vals2=np.array([1,np.nan,3,4])
vals2.dtype

dtype('float64')

In [72]:
1+np.nan

nan

In [73]:
vals2.sum()

nan

In [75]:
pd.Series([1,np.nan,None])

0    1.0
1    NaN
2    NaN
dtype: float64

In [78]:
data=pd.Series([1,np.nan,2,None,pd.NA], dtype='Int32')  # dtype='Int32'가 nullable 타입
data

0       1
1    <NA>
2       2
3    <NA>
4    <NA>
dtype: Int32

In [79]:
data.isnull()

0    False
1     True
2    False
3     True
4     True
dtype: bool

In [80]:
index = [('California', 2010), ('California', 2020),
         ('New York', 2010), ('New York', 2020),
         ('Texas', 2010), ('Texas', 2020)]
populations = [37253956, 39538223,
               19378102, 20201249,
               25145561, 29145505]
pop = pd.Series(populations, index=index)
pop

(California, 2010)    37253956
(California, 2020)    39538223
(New York, 2010)      19378102
(New York, 2020)      20201249
(Texas, 2010)         25145561
(Texas, 2020)         29145505
dtype: int64

In [83]:
%xmode plain

Exception reporting mode: Plain


In [86]:
pop[('California',2010):('Texas',2010)]

(California, 2010)    37253956
(California, 2020)    39538223
(New York, 2010)      19378102
(New York, 2020)      20201249
(Texas, 2010)         25145561
dtype: int64

In [88]:
pop[[i for i in pop.index if i[1] == 2010]]  # messy munging(list comprehension)

(California, 2010)    37253956
(New York, 2010)      19378102
(Texas, 2010)         25145561
dtype: int64

In [89]:
index = pd.MultiIndex.from_tuples(index)
index

MultiIndex([('California', 2010),
            ('California', 2020),
            (  'New York', 2010),
            (  'New York', 2020),
            (     'Texas', 2010),
            (     'Texas', 2020)],
           )

In [91]:
pop = pop.reindex(index) # 인덱스의 계층적 표현
pop

California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Texas       2010    25145561
            2020    29145505
dtype: int64

In [92]:
pop[:,2010]

California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [93]:
pop

California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Texas       2010    25145561
            2020    29145505
dtype: int64

In [94]:
pop_df = pop.unstack()
pop_df

2010      2020
California  37253956  39538223
New York    19378102  20201249
Texas       25145561  29145505

In [95]:
pop_df = pd.DataFrame({'total': pop,
                       'under18': [9284094, 8898092,
                                   4318033, 4181528,
                                   6879014, 7432474]})
pop_df

total  under18
California 2010  37253956  9284094
           2020  39538223  8898092
New York   2010  19378102  4318033
           2020  20201249  4181528
Texas      2010  25145561  6879014
           2020  29145505  7432474

In [97]:
f_u18=pop_df['under18']/pop_df['total']
f_u18

California  2010    0.249211
            2020    0.225050
New York    2010    0.222831
            2020    0.206994
Texas       2010    0.273568
            2020    0.255013
dtype: float64

In [98]:
f_u18.unstack()

2010      2020
California  0.249211  0.225050
New York    0.222831  0.206994
Texas       0.273568  0.255013

In [99]:
df = pd.DataFrame(np.random.rand(4, 2),
                  index=[['a', 'a', 'b', 'b'], [1, 2, 1, 2]],  # 다중 인덱스
                  columns=['data1', 'data2'])
df

data1     data2
a 1  0.469944  0.641426
  2  0.939596  0.539447
b 1  0.946514  0.557340
  2  0.378477  0.056556

In [100]:
pd.MultiIndex.from_arrays([['a', 'a', 'b', 'b'], [1, 2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [101]:
pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('b', 1), ('b', 2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [102]:
pd.MultiIndex.from_product([['a', 'b'], [1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [103]:
pd.MultiIndex(levels=[['a', 'b'], [1, 2]],
              codes=[[0, 0, 1, 1], [0, 1, 0, 1]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2)],
           )

In [104]:
pop

California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Texas       2010    25145561
            2020    29145505
dtype: int64

In [105]:
pop.index

MultiIndex([('California', 2010),
            ('California', 2020),
            (  'New York', 2010),
            (  'New York', 2020),
            (     'Texas', 2010),
            (     'Texas', 2020)],
           )

In [106]:
pop.index.names=['state','year']

In [107]:
pop.index

MultiIndex([('California', 2010),
            ('California', 2020),
            (  'New York', 2010),
            (  'New York', 2020),
            (     'Texas', 2010),
            (     'Texas', 2020)],
           names=['state', 'year'])

In [108]:
index = pd.MultiIndex.from_product([[2013, 2014], [1, 2]],
                                   names=['year', 'visit'])
columns = pd.MultiIndex.from_product([['Bob', 'Guido', 'Sue'], ['HR', 'Temp']],
                                     names=['subject', 'type'])

In [109]:
index

MultiIndex([(2013, 1),
            (2013, 2),
            (2014, 1),
            (2014, 2)],
           names=['year', 'visit'])

In [110]:
columns

MultiIndex([(  'Bob',   'HR'),
            (  'Bob', 'Temp'),
            ('Guido',   'HR'),
            ('Guido', 'Temp'),
            (  'Sue',   'HR'),
            (  'Sue', 'Temp')],
           names=['subject', 'type'])

In [111]:
data = np.round(np.random.randn(4, 6), 1)
data[:, ::2] *= 10
data += 37

# create the DataFrame
health_data = pd.DataFrame(data, index=index, columns=columns)
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      60.0  37.2  20.0  36.8  30.0  38.4
     2      46.0  36.4  30.0  36.1  27.0  37.9
2014 1      44.0  35.9  29.0  38.0  28.0  37.8
     2      38.0  36.9  29.0  37.9  42.0  37.2

In [112]:
health_data['Guido']

type          HR  Temp
year visit            
2013 1      20.0  36.8
     2      30.0  36.1
2014 1      29.0  38.0
     2      29.0  37.9

In [113]:
pop['California',2010]

37253956

In [114]:
pop['California']

year
2010    37253956
2020    39538223
dtype: int64

In [115]:
pop

state       year
California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Texas       2010    25145561
            2020    29145505
dtype: int64

In [116]:
pop[:,2010]

state
California    37253956
New York      19378102
Texas         25145561
dtype: int64

In [118]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      60.0  37.2  20.0  36.8  30.0  38.4
     2      46.0  36.4  30.0  36.1  27.0  37.9
2014 1      44.0  35.9  29.0  38.0  28.0  37.8
     2      38.0  36.9  29.0  37.9  42.0  37.2

In [119]:
health_data['Guido','HR']

year  visit
2013  1        20.0
      2        30.0
2014  1        29.0
      2        29.0
Name: (Guido, HR), dtype: float64

In [120]:
health_data[2013,1]

KeyError: (2013, 1)

In [122]:
health_data.iloc[:2,:2]

subject      Bob      
type          HR  Temp
year visit            
2013 1      60.0  37.2
     2      46.0  36.4

In [123]:
health_data

subject      Bob       Guido         Sue      
type          HR  Temp    HR  Temp    HR  Temp
year visit                                    
2013 1      60.0  37.2  20.0  36.8  30.0  38.4
     2      46.0  36.4  30.0  36.1  27.0  37.9
2014 1      44.0  35.9  29.0  38.0  28.0  37.8
     2      38.0  36.9  29.0  37.9  42.0  37.2

In [124]:
health_data.loc[:,('Bob','HR')]

year  visit
2013  1        60.0
      2        46.0
2014  1        44.0
      2        38.0
Name: (Bob, HR), dtype: float64

In [125]:
health_data.loc[(:,1),(:'HR')]

SyntaxError: invalid syntax (4237114085.py, line 1)

In [126]:
idx=pd.IndexSlice
health_data.loc[idx[:,1],idx[:,'HR']]

subject      Bob Guido   Sue
type          HR    HR    HR
year visit                  
2013 1      60.0  20.0  30.0
2014 1      44.0  29.0  28.0

In [127]:
index = pd.MultiIndex.from_product([['a', 'c', 'b'], [1, 2]])
data = pd.Series(np.random.rand(6), index=index)
data.index.names = ['char', 'int']
data

char  int
a     1      0.036529
      2      0.934924
c     1      0.442587
      2      0.522154
b     1      0.418960
      2      0.519315
dtype: float64

In [130]:
%xmode plain

Exception reporting mode: Plain


In [133]:
data=data.sort_index()
data

char  int
a     1      0.036529
      2      0.934924
b     1      0.418960
      2      0.519315
c     1      0.442587
      2      0.522154
dtype: float64

In [134]:
data['a':'b']

char  int
a     1      0.036529
      2      0.934924
b     1      0.418960
      2      0.519315
dtype: float64

In [135]:
data['a']

int
1    0.036529
2    0.934924
dtype: float64

In [136]:
data['b']

int
1    0.418960
2    0.519315
dtype: float64

In [137]:
pop

state       year
California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Texas       2010    25145561
            2020    29145505
dtype: int64

In [138]:
pop.unstack()

year            2010      2020
state                         
California  37253956  39538223
New York    19378102  20201249
Texas       25145561  29145505

In [139]:
pop.unstack(level=0)

state  California  New York     Texas
year                                 
2010     37253956  19378102  25145561
2020     39538223  20201249  29145505

In [140]:
pop.unstack(level=1)

year            2010      2020
state                         
California  37253956  39538223
New York    19378102  20201249
Texas       25145561  29145505

In [141]:
pop.reset_index()

state  year         0
0  California  2010  37253956
1  California  2020  39538223
2    New York  2010  19378102
3    New York  2020  20201249
4       Texas  2010  25145561
5       Texas  2020  29145505

In [142]:
pop

state       year
California  2010    37253956
            2020    39538223
New York    2010    19378102
            2020    20201249
Texas       2010    25145561
            2020    29145505
dtype: int64

In [143]:
pop.reset_index()

state  year         0
0  California  2010  37253956
1  California  2020  39538223
2    New York  2010  19378102
3    New York  2020  20201249
4       Texas  2010  25145561
5       Texas  2020  29145505

In [144]:
pop.reset_index(name='population')

state  year  population
0  California  2010    37253956
1  California  2020    39538223
2    New York  2010    19378102
3    New York  2020    20201249
4       Texas  2010    25145561
5       Texas  2020    29145505

In [145]:
def make_df(cols, ind):
    """Quickly make a DataFrame"""
    data = {c: [str(c) + str(i) for i in ind]
            for c in cols}
    return pd.DataFrame(data, ind)

# example DataFrame
make_df('ABC', range(3))

A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [146]:
x = [[1, 2],
     [3, 4]]
np.concatenate([x, x], axis=1)

array([[1, 2, 1, 2],
       [3, 4, 3, 4]])